### ISSUE TITLE
Unresolved reference to "GuzzleHttp"

### ISSUE THREAD

**Issue by SundialServices** [jens-reichert/W3C-Validator#1]
Your source-code as posted makes several references to "GuzzleHttp" which are not resolved.

**Comment by jens-reichert** [comment]
You mean, that the Guzzle Client is instanciated in the Constructor, instead of passing it as a dependency?

**Comment by jens-reichert** [comment]
Guzzle Client can now be injected into the HtmlValidator::class Constructor
